In [6]:
import numpy as np

# Example categories
categories = ['cat', 'dog', 'bird', 'cat', 'bird', 'dog']

# Get unique categories and map each to an index
unique_categories = sorted(set(categories))
category_to_index = {category: idx for idx, category in enumerate(unique_categories)}

# One-hot encoding
one_hot_encoded = np.zeros((len(categories), len(unique_categories)))

for i, category in enumerate(categories):
    index = category_to_index[category]
    one_hot_encoded[i, index] = 1

print("Unique Categories:", unique_categories)
print("One-Hot Encoded Matrix:")
print(one_hot_encoded)


Unique Categories: ['bird', 'cat', 'dog']
One-Hot Encoded Matrix:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [5]:
print(one_hot_encoded)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
